data:
  data_file: /d0/kvandersande/index_sharps.csv
  dim: 128
  val_split: 0
  features: []
  test: ''
meta:
  user: kierav
  project: sharps-embeddings
  resume: false
  tags: []
  id: None
model:
  base_channel_size: 16
  channels: 4
  checkpoint_location: None
  load_checkpoint: false
  latent_dim: 20
training:
  batch_size: 256
  epochs: 10
  iterations: 10
  train_frac: 0.1